
trigger:
  branches:
    include:
      - features/*
      - main

pool: Agent
stages:
  - stage: terraform_init_stage
    displayName: i am doing init
    jobs:
      - job: init
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest' 
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/'
            backendServiceArm: 'latest-svc'
            backendAzureRmStorageAccountName: 'tokri'
            backendAzureRmContainerName: 'tijori'
            backendAzureRmKey: 'abc.tfstate'
